### ISSUE TITLE
On the future development of this plugin

### ISSUE THREAD

**Issue by fujimotos** [uken/fluent-plugin-nsq#4]
Hi @uken team (CC: @gihad). First, thanks for developing such a great plugin!

We are @fluent-plugins-nursery team who try to maintain orphaned Fluentd plugins
and keep them updated.

It seems to us that the development of this plugin has been stagnating for a while.
For example:

 1. The last update (7cd2fd7) was more than two years ago.
 2. A bug report #3 has been left unaddessed for a year.
 3. It does not work with the latest Fluentd version anymore (See #2)

Since a sizable number of users are still relying on this plugin, we want to adopt
this plugin as well.

So the question is: is it possible to transfer the ownership of this project to
fluent-plugins-nursery? If you can, we'd continue the development of this work as
part of our program to sustain the ecosystem.

We are really looking forward to hearing back from you!

**Comment by gihad** [comment]
Hi, it's also worth noting that the bug report you mentioned is the only issue opened in the repo and that PR is also the only one, I wasn't monitoring this project - thanks for bringing that to my attention. To me it didn't look like a sizeable number of users are still relying on this plugin.

The plugin is still used by us currently and works for our purposes, but you are right that we don't have resources to enhance the plugin with requests from the community. I wouldn't transfer ownership however I would welcome someone from the community as the official maintainer of the project.

Thanks,
Gihad

**Comment by cosmo0920** [comment]
> I wouldn't transfer ownership however I would welcome someone from the community as the official maintainer of the project.

Like as ES plugin? It's welcome for us.
Thank you for your response.

**Comment by fujimotos** [comment]
Thank you @gihad for considering our request.

> Hi, it's also worth noting that the bug report you mentioned is the only issue opened in the repo and that PR is also the only one, I wasn't monitoring this project - thanks for bringing that to my attention. To me it didn't look like a sizeable number of users are still relying on this plugin.

Yes, I admit my original comment is a bit exaggrating.

That being said, I talked with my team members (including @cosmo0920) after receiving
your reply and they were still interested in maintaining this plugin, especially in developing
it further to be compatible with Fluentd v1.0.

On the basis of above, we would like to take the maitainership of this plugin. 

> however I would welcome someone from the community as the official maintainer of the project.

Thanks for the very kind offer. We have talked about your offer too, and come to the
conclusion that @cosmo0920 should be the right person for the role. Please add him
as a maintainer of this project; Then we'll start the development soon.

**Comment by gihad** [comment]
Great! I added @cosmo0920 to the repo and also listed him as the maintainer in the README file.
Thank you.

**Comment by cosmo0920** [comment]
@lxfontes Could you add me to fluent-plugin-nsq rubygems owner?
My e-mail address is `cosmo0920.oucc@gmail.com`.
